version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/var/www/html    
    depends_on:
      - php
    networks:
      - internal

  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - internal

  mysql:
    image: mariadb:10.5
    container_name: mysql
    environment:
      MYSQL_DATABASE: projet_zero_sdf
      MYSQL_USER: ibrahim
      MYSQL_PASSWORD: mdpAmodifier
      MYSQL_ROOT_PASSWORD: mdpAmodifier
      INSTALL_SAKILA : 1
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - internal
    # restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8085:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge
